spring:
  main:
    banner-mode: off
  flyway:
    enabled: true

  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://localhost:5432/knytest
    driver-class-name: org.postgresql.Driver
    username: knytest
    password: fzhsNuwgmJsphjyoxgecsofd9zm3uk

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
